const drawingTool = [
  // { header: "Lines, Trend lines and Rays:" },
  {
    name: "Line Segment",
    annotationType: "line",
    group: "Lines, Trend lines and Rays:",
    icon: "ac-line",
  },
  {
    name: "Horizontal Line",
    annotationType: "horizontal-line",
    group: "Lines, Trend lines and Rays:",
    icon: "ac-horizontal-line",
  },
  {
    name: "Vertical Line",
    annotationType: "vertical-line",
    group: "Lines, Trend lines and Rays:",
    icon: "ac-vertical-line",
  },
  {
    name: "Infinite Line",
    annotationType: "infinite-line",
    group: "Lines, Trend lines and Rays:",
    icon: "ac-infinite-line",
  },
  {
    name: "Ray",
    annotationType: "ray",
    group: "Lines, Trend lines and Rays:",
    icon: "ac-ray",
  },
  // { header: "Geometric shapes:" },
  {
    name: "Triangle",
    annotationType: "triangle",
    group: "Geometric shapes:",
    icon: "ac-triangle",
  },
  {
    name: "Rectangle",
    annotationType: "rectangle",
    group: "Geometric shapes:",
    icon: "ac-rectangle",
  },
  {
    name: "Ellipse",
    value: "ellipse",
    group: "Geometric shapes:",
    icon: "ac-ellipse",
  },
  // { header: "Other tools:" },
  {
    name: "Horizontal Range",
    annotationType: "horizontal-range",
    group: "Other tools:",
    icon: "ac-horizontal-range",
  },
  {
    name: "Vertical Range",
    annotationType: "vertical-range",
    group: "Other tools:",
    icon: "ac-vertical-range",
  },
  // { header: "Other tools:" },
  {
    name: "Trend Channel",
    annotationType: "trend-channel",
    group: "Other tools:",
    icon: "ac-trend-channel",
  },
  {
    name: "Finite Trend Channel",
    annotationType: "finite-trend-channel",
    group: "Other tools:",
    icon: "ac-finite-trend-channel",
  },
  {
    name: "Andrew's Pitchfork",
    annotationType: "andrews-pitchfork",
    group: "Other tools:",
    icon: "ac-andrews-pitchfork",
  },
  // { header: "Fibonacci tools:" },
  {
    name: "Fibonacci Fan",
    annotationType: "fibonacci-fan",
    group: "Other tools:",
    icon: "ac-fibonacci-fan",
  },
  {
    name: "Fibonacci Arc",
    annotationType: "fibonacci-arc",
    group: "Other tools:",
    icon: "ac-fibonacci-arc",
  },
  {
    name: "Fibonacci Retracement",
    annotationType: "fibonacci-retracement",
    group: "Other tools:",
    icon: "ac-fibonacci-retracement",
  },
  {
    name: "Fibonacci Time",
    annotationType: "fibonacci-timezones",
    group: "Other tools:",
    icon: "ac-fibonacci-timezones",
  },
];

export default drawingTool;
