const markerType = [
  {
    name: "Up Arrow",
    markerType: "arrowUp",
    markerAnchor: "center-top",
    icon: "ac-arrow-up-square",
    annotationType: "marker",
  },
  {
    name: "Down Arrow",
    markerType: "arrow-down",
    markerAnchor: "center-bottom",
    icon: "ac-arrow-down-square",
    annotationType: "marker",
  },
  {
    name: "Left Arrow",
    markerType: "arrow-left",
    markerAnchor: "left-center",
    icon: "ac-arrow-left-square",
    annotationType: "marker",
  },
  {
    name: "Right Arrow",
    markerType: "arrow-right",
    markerAnchor: "right-center",
    icon: "ac-arrow-right-square",
    annotationType: "marker",
  },
  {
    name: "Head Arrow",
    markerType: "arrowHead",
    markerAnchor: "right-center",
    icon: "ac-head-arrow",
    annotationType: "marker",
  },
  {
    name: "Cross",
    markerType: "cross",
    markerAnchor: "center",
    icon: "ac-cross",
    annotationType: "marker",
  },
  {
    name: "Diagonal cross",
    markerType: "diagonal-cross",
    markerAnchor: "center",
    icon: "ac-diagonal-cros",
    annotationType: "marker",
  },
  {
    name: "Diamond",
    markerType: "diamond",
    markerAnchor: "center",
    icon: "ac-diamond",
    annotationType: "marker",
  },
  {
    name: "Pentagon",
    markerType: "pentagon",
    markerAnchor: "center",
    icon: "ac-pentagon",
    annotationType: "marker",
  },
  {
    name: "Square",
    markerType: "square",
    markerAnchor: "center",
    icon: "ac-square",
    annotationType: "marker",
  },
  {
    name: "Star 1",
    markerType: "star10",
    markerAnchor: "center",
    icon: "ac-star-1",
    annotationType: "marker",
  },
  {
    name: "Star 2",
    markerType: "star4",
    markerAnchor: "center",
    icon: "ac-star-2",
    annotationType: "marker",
  },
  {
    name: "Star 3",
    markerType: "star5",
    markerAnchor: "center",
    icon: "ac-star-3",
    annotationType: "marker",
  },
  {
    name: "Star 4",
    markerType: "star6",
    markerAnchor: "center",
    icon: "ac-star-4",
    annotationType: "marker",
  },
  {
    name: "Star 5",
    markerType: "star7",
    markerAnchor: "center",
    icon: "ac-star-5",
    annotationType: "marker",
  },
  {
    name: "Trapezium",
    markerType: "trapezium",
    markerAnchor: "center",
    icon: "ac-trapezium",
    annotationType: "marker",
  },
  {
    name: "Triangle Up",
    markerType: "triangle-up",
    markerAnchor: "center-top",
    icon: "ac-triangle-up",
    annotationType: "marker",
  },
  {
    name: "Triangle Down",
    markerType: "triangle-down",
    markerAnchor: "center-bottom",
    icon: "ac-triangle-down",
    annotationType: "marker",
  },
  {
    name: "Triangle Left",
    markerType: "triangle-left",
    markerAnchor: "left-center",
    icon: "ac-triangle-left",
    annotationType: "marker",
  },
  {
    name: "Triangle Right",
    markerType: "triangle-right",
    markerAnchor: "right-center",
    icon: "ac-triangle-right",
    annotationType: "marker",
  },
];

export default markerType;
